# Codomax Internship — Module 2: Data Analysis with Python

## Day 5 — Pandas and NumPy Fundamentals

In [1]:
import numpy as np
import pandas as pd

print("NumPy:", np.__version__)
print("Pandas:", pd.__version__)

NumPy: 2.0.2
Pandas: 2.2.2

In [2]:
marks = np.array([78, 85, 92, 67, 74, 88, 61])
print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Maximum:", np.max(marks))
print("Minimum:", np.min(marks))
print("Standard Deviation:", round(np.std(marks), 2))

Mean: 77.85714285714286
Median: 78.0
Maximum: 92
Minimum: 61
Standard Deviation: 10.49

In [3]:
data = {
    "Name": ["Rahul", "Anita", "Kiran", "Priya"],
    "Marks": [78, 92, 65, 88],
    "City": ["Bengaluru", "Mysuru", "Hubballi", "Kalaburagi"]
}
sample_df = pd.DataFrame(data)
sample_df

    Name  Marks        City
0  Rahul     78   Bengaluru
1  Anita     92      Mysuru
2  Kiran     65    Hubballi
3  Priya     88  Kalaburagi

## Day 6 — CSV Import and Data Exploration

In [4]:
practice_data = {
    "Student_ID": [101,102,103,104,105,106,106,107,108],
    "Name": ["Rahul","Anita","Kiran","Priya","Arjun","Meena","Meena","Sara","Vijay"],
    "Marks": [78,92,np.nan,88,31,67,67,84,np.nan],
    "City": ["Bengaluru","Mysuru","Hubballi","Kalaburagi",None,"Mysuru","Mysuru","Kalaburagi","Hubballi"]
}
df = pd.DataFrame(practice_data)
df.to_csv("student_performance.csv", index=False)
df = pd.read_csv("student_performance.csv")
df

   Student_ID   Name  Marks        City
0         101  Rahul   78.0   Bengaluru
1         102  Anita   92.0      Mysuru
2         103  Kiran    NaN    Hubballi
3         104  Priya   88.0  Kalaburagi
4         105  Arjun   31.0         NaN
5         106  Meena   67.0      Mysuru
6         106  Meena   67.0      Mysuru
7         107   Sara   84.0  Kalaburagi
8         108  Vijay    NaN    Hubballi

In [5]:
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())
display(df.head())
df.info()

Shape: (9, 4)
Columns: ['Student_ID', 'Name', 'Marks', 'City']

   Student_ID   Name  Marks        City
0         101  Rahul   78.0   Bengaluru
1         102  Anita   92.0      Mysuru
2         103  Kiran    NaN    Hubballi
3         104  Priya   88.0  Kalaburagi
4         105  Arjun   31.0         NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  9 non-null      int64
 1   Name        9 non-null      object
 2   Marks       7 non-null      float64
 3   City        8 non-null      object
dtypes: float64(1), int64(1), object(2)
memory usage: 420.0+ bytes

In [6]:
df.describe(include="all")

        Student_ID   Name      Marks    City
count     9.000000      9   7.000000       8
unique         NaN      8        NaN       4
top            NaN  Meena        NaN  Mysuru
freq           NaN      2        NaN       3
mean    104.666667    NaN  72.428571     NaN
std       2.345208    NaN  20.678952     NaN
min     101.000000    NaN  31.000000     NaN
25%     103.000000    NaN  67.000000     NaN
50%     105.000000    NaN  78.000000     NaN
75%     106.000000    NaN  86.000000     NaN
max     108.000000    NaN  92.000000     NaN

## Day 7 — Data Cleaning

In [7]:
print("Missing values:")
print(df.isnull().sum())
print("\nDuplicate rows:", df.duplicated().sum())

Missing values:
Student_ID    0
Name          0
Marks         2
City          1
dtype: int64

Duplicate rows: 1

In [8]:
clean_df = df.drop_duplicates().copy()
print("Rows before:", len(df))
print("Rows after duplicate removal:", len(clean_df))

Rows before: 9
Rows after duplicate removal: 8

In [9]:
median_marks = clean_df["Marks"].median()
clean_df["Marks"] = clean_df["Marks"].fillna(median_marks)
clean_df["City"] = clean_df["City"].fillna("Unknown")

print("Median used for missing Marks:", median_marks)
print("\nMissing values after cleaning:")
print(clean_df.isnull().sum())

Median used for missing Marks: 81.0

Missing values after cleaning:
Student_ID    0
Name          0
Marks         0
City          0
dtype: int64

In [10]:
clean_df["Marks"] = pd.to_numeric(clean_df["Marks"], errors="coerce")
clean_df = clean_df.sort_values("Student_ID").reset_index(drop=True)
clean_df

   Student_ID   Name  Marks        City
0         101  Rahul   78.0   Bengaluru
1         102  Anita   92.0      Mysuru
2         103  Kiran   81.0    Hubballi
3         104  Priya   88.0  Kalaburagi
4         105  Arjun   31.0     Unknown
5         106  Meena   67.0      Mysuru
6         107   Sara   84.0  Kalaburagi
7         108  Vijay   81.0    Hubballi

## Day 8 — Basic Data Analysis

In [11]:
print("Average:", round(clean_df["Marks"].mean(), 2))
print("Median:", clean_df["Marks"].median())
print("Highest:", clean_df["Marks"].max())
print("Lowest:", clean_df["Marks"].min())

Average: 75.25
Median: 81.0
Highest: 92.0
Lowest: 31.0

In [14]:
clean_df["Status"] = np.where(clean_df["Marks"] >= 35, "Pass", "Fail")
display(clean_df[["Name","Marks","Status"]])
print(clean_df["Status"].value_counts())

    Name  Marks Status
0  Rahul   78.0   Pass
1  Anita   92.0   Pass
2  Kiran   81.0   Pass
3  Priya   88.0   Pass
4  Arjun   31.0   Fail
5  Meena   67.0   Pass
6   Sara   84.0   Pass
7  Vijay   81.0   Pass

Status
Pass    7
Fail    1
Name: count, dtype: int64

In [15]:
high_scorers = clean_df[clean_df["Marks"] >= 75].sort_values("Marks", ascending=False)
high_scorers

   Student_ID   Name  Marks        City Status
1         102  Anita   92.0      Mysuru   Pass
3         104  Priya   88.0  Kalaburagi   Pass
6         107   Sara   84.0  Kalaburagi   Pass
2         103  Kiran   81.0    Hubballi   Pass
7         108  Vijay   81.0    Hubballi   Pass
0         101  Rahul   78.0   Bengaluru   Pass

In [16]:
city_analysis = clean_df.groupby("City", as_index=False).agg(
    Students=("Student_ID","count"),
    Average_Marks=("Marks","mean"),
    Highest_Marks=("Marks","max")
)
city_analysis["Average_Marks"] = city_analysis["Average_Marks"].round(2)
city_analysis

         City  Students  Average_Marks  Highest_Marks
0   Bengaluru         1           78.0           78.0
1    Hubballi         2           81.0           81.0
2  Kalaburagi         2           86.0           88.0
3      Mysuru         2           79.5           92.0
4     Unknown         1           31.0           31.0

## Key Findings

In [17]:
top_student = clean_df.loc[clean_df["Marks"].idxmax()]
lowest_student = clean_df.loc[clean_df["Marks"].idxmin()]
total = len(clean_df)
passed = (clean_df["Status"] == "Pass").sum()
failed = (clean_df["Status"] == "Fail").sum()

print("Total students:", total)
print("Average marks:", round(clean_df["Marks"].mean(), 2))
print("Pass count:", passed)
print("Fail count:", failed)
print("Pass rate:", round(passed / total * 100, 2), "%")
print("Top performer:", top_student["Name"], "-", top_student["Marks"])
print("Lowest performer:", lowest_student["Name"], "-", lowest_student["Marks"])

Total students: 8
Average marks: 75.25
Pass count: 7
Fail count: 1
Pass rate: 87.5 %
Top performer: Anita - 92.0
Lowest performer: Arjun - 31.0

## Export Cleaned Dataset

In [18]:
clean_df.to_csv("cleaned_student_performance.csv", index=False)
print("Saved: cleaned_student_performance.csv")

# For Colab download, uncomment:
# from google.colab import files
# files.download("cleaned_student_performance.csv")

Saved: cleaned_student_performance.csv